// src/lib/ics.ts
export function downloadICS(filename: string, ics: string) {
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 0)
}

const DEFAULT_REMINDER_MIN = 10 // fallback if nothing is provided; Settings can override this

export type IcsCalendarEvent = {
  title: string
  start: Date
  end?: Date
  uid?: string
  description?: string
  location?: string
  categories?: string[]
  remindMinutes?: number
}

function fmt(date: Date) {
  const pad = (n: number) => n.toString().padStart(2, '0')
  const yyyy = date.getFullYear()
  const mm = pad(date.getMonth() + 1)
  const dd = pad(date.getDate())
  const hh = pad(date.getHours())
  const mi = pad(date.getMinutes())
  const ss = pad(date.getSeconds())
  return `${yyyy}${mm}${dd}T${hh}${mi}${ss}` // floating local time
}

function escapeIcsText(value: string) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\r?\n/g, '\\n')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;')
}

function foldIcsLine(line: string) {
  const max = 73
  if (line.length <= max) return line
  const chunks: string[] = []
  for (let i = 0; i < line.length; i += max) {
    chunks.push(`${i === 0 ? '' : ' '}${line.slice(i, i + max)}`)
  }
  return chunks.join('\r\n')
}

function normalizeReminder(minutes: number | undefined, fallback: number) {
  return typeof minutes === 'number' ? Math.max(0, Math.floor(minutes)) : fallback
}

export function buildIcsCalendar(
  events: IcsCalendarEvent[],
  opts?: {
    name?: string
    description?: string
    groupId?: string
    defaultReminderMin?: number
  }
) {
  const name = opts?.name ?? 'Athan Reminders'
  const groupId = opts?.groupId ?? 'ATHAN-PWA'
  const defaultReminderMin = opts?.defaultReminderMin ?? DEFAULT_REMINDER_MIN
  const generatedAt = fmt(new Date())
  const seenUids = new Set<string>()
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    foldIcsLine(`X-WR-CALNAME:${escapeIcsText(name)}`),
    foldIcsLine(`X-WR-CALDESC:${escapeIcsText(opts?.description ?? `${name} - generated by Athan PWA`)}`),
    'PRODID:-//Athan PWA//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH'
  ]

  events.forEach((event, index) => {
    const start = fmt(event.start)
    const end = fmt(event.end ?? new Date(event.start.getTime() + 5 * 60 * 1000))
    const baseUid = event.uid ?? `${start}-${index}@${groupId}`
    let uid = baseUid
    let duplicateCount = 1
    while (seenUids.has(uid)) {
      duplicateCount += 1
      uid = `${baseUid}-${duplicateCount}`
    }
    seenUids.add(uid)

    const categories = Array.from(new Set([...(event.categories ?? []), groupId, 'Athan-PWA']))
    const minutes = normalizeReminder(event.remindMinutes, defaultReminderMin)

    lines.push(
      'BEGIN:VEVENT',
      foldIcsLine(`UID:${escapeIcsText(uid)}`),
      `DTSTAMP:${generatedAt}`,
      `DTSTART:${start}`,
      `DTEND:${end}`,
      foldIcsLine(`SUMMARY:${escapeIcsText(event.title)}`),
      foldIcsLine(`CATEGORIES:${categories.map(escapeIcsText).join(',')}`),
      foldIcsLine(`X-ATHAN-GROUP:${escapeIcsText(groupId)}`)
    )

    if (event.description) lines.push(foldIcsLine(`DESCRIPTION:${escapeIcsText(event.description)}`))
    if (event.location) lines.push(foldIcsLine(`LOCATION:${escapeIcsText(event.location)}`))

    lines.push(
      'BEGIN:VALARM',
      `TRIGGER:-PT${minutes}M`,
      'ACTION:DISPLAY',
      foldIcsLine(`DESCRIPTION:${escapeIcsText(event.title)}`),
      'END:VALARM',
      'END:VEVENT'
    )
  })

  lines.push('END:VCALENDAR')
  return lines.join('\r\n')
}

type IcsItem = {
  title: string
  when: Date
  /** Minutes before the event to trigger a popup reminder (VALARM). Default 10. */
  remindMinutes?: number
  /** Optional custom text to append to SUMMARY (overrides default "(X min before)"). */
  summarySuffix?: string
}

export function buildIcsForDates(
  items: IcsItem[],
  name = 'Athan Reminders',
  groupId = 'ATHAN-PWA',
  defaultReminderMin = DEFAULT_REMINDER_MIN
) {
  return buildIcsCalendar(items.map((it, i) => {
    const minutes = normalizeReminder(it.remindMinutes, defaultReminderMin)
    const suffix = typeof it.summarySuffix === 'string' ? it.summarySuffix : `(${minutes} min before)`
    const title = `${it.title}${suffix ? ` ${suffix}` : ''}`
    return {
      title,
      start: it.when,
      end: new Date(it.when.getTime() + 5 * 60 * 1000),
      uid: `${fmt(it.when)}-${i}@${groupId}`,
      description: it.title,
      categories: [groupId],
      remindMinutes: minutes
    }
  }), {
    name,
    description: `${name} - generated by Athan PWA`,
    groupId,
    defaultReminderMin
  })
}

// ---------- Prayer-specific helpers ----------

export type DayPrayers = {
  fajr: Date
  sunrise: Date
  dhuhr: Date
  asr: Date
  maghrib: Date
  isha: Date
}

/**
 * Make exactly 11 entries for a day:
 *  6 base prayers: Fajr, Sunrise, Dhuhr, Asr, Maghrib, Isha
 *  4 before-next reminders: (Sunrise - offset), (Asr - offset), (Maghrib - offset), (Isha - offset)
 *  1 fixed Isha reminder at HH:mm if provided (e.g. "22:00")
 *
 * Rule: offset is clamped to at least 1 minute so reminder events never collide with the next prayer time.
 */
export function buildIcsForPrayerDay(
  day: DayPrayers,
  offsetMinInput: number,
  opts?: {
    /** Optional fixed local time (HH:mm) for a second Isha reminder, e.g., "22:00". */
    ishaFixedTime?: string
    /** Calendar name and group id for easier deletion. */
    name?: string
    groupId?: string
    /** Override default VALARM minutes for generated items (default 10). */
    defaultReminderMin?: number
  }
) {
  const name = opts?.name ?? 'Athan Reminders'
  const groupId = opts?.groupId ?? 'ATHAN-PWA'
  const defaultReminderMin = opts?.defaultReminderMin ?? DEFAULT_REMINDER_MIN

  const offsetMin = Math.max(1, Math.floor(offsetMinInput || 0)) // clamp to at least 1 min
  const minus = (d: Date, m: number) => new Date(d.getTime() - m * 60 * 1000)
  const items: IcsItem[] = []

  // 6 base prayers
  items.push(
    { title: 'Fajr', when: day.fajr },
    { title: 'Sunrise', when: day.sunrise },
    { title: 'Dhuhr', when: day.dhuhr },
    { title: 'Asr', when: day.asr },
    { title: 'Maghrib', when: day.maghrib },
    { title: 'Isha', when: day.isha }
  )

  // 4 reminders before NEXT prayer (scheduled at next prayer time minus offset)
  items.push(
    { title: `Fajr reminder before Sunrise (${offsetMin}m)`, when: minus(day.sunrise, offsetMin), remindMinutes: defaultReminderMin, summarySuffix: '' },
    { title: `Dhuhr reminder before Asr (${offsetMin}m)`, when: minus(day.asr, offsetMin), remindMinutes: defaultReminderMin, summarySuffix: '' },
    { title: `Asr reminder before Maghrib (${offsetMin}m)`, when: minus(day.maghrib, offsetMin), remindMinutes: defaultReminderMin, summarySuffix: '' },
    { title: `Maghrib reminder before Isha (${offsetMin}m)`, when: minus(day.isha, offsetMin), remindMinutes: defaultReminderMin, summarySuffix: '' }
  )

  // 1 fixed Isha reminder at a user time (e.g., "22:00")
  if (opts?.ishaFixedTime) {
    const [hh, mm] = opts.ishaFixedTime.split(':').map(n => parseInt(n, 10))
    if (Number.isFinite(hh) && Number.isFinite(mm)) {
      const ish = new Date(day.isha)
      ish.setHours(hh!, mm!, 0, 0)
      items.push({ title: 'Isha (custom reminder)', when: ish, remindMinutes: defaultReminderMin, summarySuffix: '' })
    }
  }

  // Exactly 11 entries/day now
  return buildIcsForDates(items, name, groupId, defaultReminderMin)
}

/** Build one ICS covering 7 consecutive days. */
export function buildIcsForWeek(
  days: DayPrayers[],
  offsetMinInput: number,
  opts?: {
    ishaFixedTime?: string
    name?: string
    groupId?: string
    defaultReminderMin?: number
  }
) {
  const name = opts?.name ?? 'Athan Reminders'
  const groupId = opts?.groupId ?? 'ATHAN-PWA'
  const defaultReminderMin = opts?.defaultReminderMin ?? DEFAULT_REMINDER_MIN
  const offsetMin = Math.max(1, Math.floor(offsetMinInput || 0))

  const chunks: string[] = []
  days.forEach((d) => {
    const single = buildIcsForPrayerDay(d, offsetMin, {
      ishaFixedTime: opts?.ishaFixedTime,
      name,
      groupId,
      defaultReminderMin
    })
    // strip VCALENDAR wrapper so we can merge events into one calendar
    const eventsBlock = single
      .split('\r\n')
      .filter(line =>
        line !== 'BEGIN:VCALENDAR' &&
        line !== 'END:VCALENDAR' &&
        !line.startsWith('VERSION') &&
        !line.startsWith('X-WR-CAL') &&
        !line.startsWith('PRODID') &&
        !line.startsWith('CALSCALE') &&
        !line.startsWith('METHOD')
      )
      .join('\r\n')
    chunks.push(eventsBlock)
  })

  const header = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `X-WR-CALNAME:${name}`,
    `X-WR-CALDESC:${name} — generated by Athan PWA (7 days)`,
    'PRODID:-//Athan PWA//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH'
  ].join('\r\n')

  return `${header}\r\n${chunks.join('\r\n')}\r\nEND:VCALENDAR`
}
